spring:
  application:
    name: schoolProject

  datasource:
    url: jdbc:postgresql://localhost:5433/schooldb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: andrewid10@gmail.com
    password: wfip lhcb frja sauo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

task:
  kafka:
    topic:
      status-updated: task-status-topic
    consumer:
      group-id: task-status-group